clean.install:
	cd blob/ && mvn clean install && cd ..
#	cd builder_roo/ && mvn clean install && cd ..
#	cd forward/ && mvn clean install && cd ..
#	cd pizza/ && mvn clean install && cd ..
	cd sample/ && mvn clean install && cd ..
run.sonar:
	cd blob/ && mvn sonar:sonar && cd ..
#	cd builder_roo/ && mvn sonar:sonar && cd ..
#	cd forward/ && mvn sonar:sonar && cd ..
#	cd pizza/ && mvn sonar:sonar && cd ..
	cd sample/ && mvn sonar:sonar && cd ..
clean:
	cd blob/ && mvn clean && cd ..
#	cd builder_roo/ && mvn clean && cd ..
#	cd forward/ && mvn clean && cd ..
#	cd pizza/ && mvn clean && cd ..
	cd sample/ && mvn clean && cd ..
