run.sonar:
	cd blob/ && mvn sonar:sonar && cd ..
	cd builder_roo/ && mvn sonar:sonar && cd ..
	cd forward/ && mvn sonar:sonar && cd ..
	cd pizza/ && mvn sonar:sonar && cd ..
	cd sample/ && mvn sonar:sonar && cd ..
clean:
	cd blob/ && mvn clean && cd ..
	cd builder_roo/ && mvn clean && cd ..
	cd forward/ && mvn clean && cd ..
	cd pizza/ && mvn clean && cd ..
	cd sample/ && mvn clean && cd ..
