run.sonar:
	cd RESTfulExample/ && mvn sonar:sonar  && cd .. 
#	cd jaxrs-jersey-spring/ && mvn sonar:sonar && cd.. 
	cd server/ && mvn sonar:sonar && cd.. 
	cd json-support/ && mvn sonar:sonar && cd.. 
clean:
	cd RESTfulExample/ && mvn clean && cd .. 
	cd jaxrs-jersey-spring/ && mvn clean && cd .. 
	cd server/ && mvn clean && cd .. 
	cd json-support/ && mvn clean && cd .. 
