clean.instal:
	cd phd/ && mvn clean install && cd ..
#	cd timit/ && mvn clean install && cd ..
run.sonar: 
	cd phd/ && mvn sonar:sonar && cd ..
#	cd timit/ && mvn sonar:sonar && cd ..
clean: 
	cd phd/ && mvn clean && cd ..
#	cd timit/ && mvn clean && cd ..
