clean.install:
	cd com.tutorialspoint/ && mvn clean install && cd .. 
	cd SpringExample/ && mvn clean install && cd .. 

run.sonar:
	cd com.tutorialspoint/ && mvn sonar:sonar && cd .. 
	cd SpringExample/ && mvn sonar:sonar && cd .. 
clean:
	cd com.tutorialspoint/ && mvn clean && cd .. 
	cd SpringExample/ && mvn clean && cd .. 


