// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.ixonos.builder.domain;

import java.lang.String;

privileged aspect Templates_Roo_JavaBean {
    
    public String Templates.getName() {
        return this.name;
    }
    
    public void Templates.setName(String name) {
        this.name = name;
    }
    
}
