clean.install:
	#cd mk/ && mvn sonar:sonar && cd .. 
	cd SpringExample/ && mvn clean install && cd ..
	#cd SpringHibernateAnnotationExample/ && mvn clean install && cd ..
run.sonar:
	#cd mk/ && mvn sonar:sonar && cd .. 
	cd SpringExample/ && mvn sonar:sonar && cd ..
	#cd SpringHibernateAnnotationExample/ && mvn sonar:sonar && cd ..
	#cd spring-hibernate1/ && mvn sonar:sonar && cd ..
clean:
	cd mk/ && mvn clean && cd .. 
	cd SpringExample/ && mvn clean && cd ..
	cd SpringHibernateAnnotationExample/ && mvn clean && cd ..
	cd spring-hibernate1/ && mvn clean && cd ..
