// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.pizzashop.domain;

import com.springsource.roo.pizzashop.domain.Symbian_general;
import com.springsource.roo.pizzashop.domain.Symbian_generalDataOnDemand;
import com.springsource.roo.pizzashop.domain.Symbian_generalIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Symbian_generalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: Symbian_generalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: Symbian_generalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: Symbian_generalIntegrationTest: @Transactional;
    
    @Autowired
    private Symbian_generalDataOnDemand Symbian_generalIntegrationTest.dod;
    
    @Test
    public void Symbian_generalIntegrationTest.testCountSymbian_generals() {
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", dod.getRandomSymbian_general());
        long count = Symbian_general.countSymbian_generals();
        Assert.assertTrue("Counter for 'Symbian_general' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testFindSymbian_general() {
        Symbian_general obj = dod.getRandomSymbian_general();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to provide an identifier", id);
        obj = Symbian_general.findSymbian_general(id);
        Assert.assertNotNull("Find method for 'Symbian_general' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Symbian_general' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testFindAllSymbian_generals() {
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", dod.getRandomSymbian_general());
        long count = Symbian_general.countSymbian_generals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Symbian_general', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Symbian_general> result = Symbian_general.findAllSymbian_generals();
        Assert.assertNotNull("Find all method for 'Symbian_general' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Symbian_general' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testFindSymbian_generalEntries() {
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", dod.getRandomSymbian_general());
        long count = Symbian_general.countSymbian_generals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Symbian_general> result = Symbian_general.findSymbian_generalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Symbian_general' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Symbian_general' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testFlush() {
        Symbian_general obj = dod.getRandomSymbian_general();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to provide an identifier", id);
        obj = Symbian_general.findSymbian_general(id);
        Assert.assertNotNull("Find method for 'Symbian_general' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySymbian_general(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Symbian_general' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testMergeUpdate() {
        Symbian_general obj = dod.getRandomSymbian_general();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to provide an identifier", id);
        obj = Symbian_general.findSymbian_general(id);
        boolean modified =  dod.modifySymbian_general(obj);
        Integer currentVersion = obj.getVersion();
        Symbian_general merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Symbian_general' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", dod.getRandomSymbian_general());
        Symbian_general obj = dod.getNewTransientSymbian_general(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Symbian_general' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Symbian_general' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void Symbian_generalIntegrationTest.testRemove() {
        Symbian_general obj = dod.getRandomSymbian_general();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Symbian_general' failed to provide an identifier", id);
        obj = Symbian_general.findSymbian_general(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Symbian_general' with identifier '" + id + "'", Symbian_general.findSymbian_general(id));
    }
    
}
