run.sonar: 
	cd SpringMVC/ && mvn sonar:sonar && cd ..
	cd spring-rest-example/ && mvn sonar:sonar && cd ..
clean: 
	cd SpringMVC/ && mvn clean && cd ..
	cd spring-rest-example/ && mvn clean && cd ..
