clean.install: 
	cd SpringMVC/ && mvn clean instal && cd ..
	cd spring-rest-example/ && mvn clean install && cd ..
	cd rest-sample/ && mvn clean install && cd ..
clean: 
	cd SpringMVC/ && mvn clean && cd ..
	cd spring-rest-example/ && mvn clean && cd ..
	cd rest-sample/ && mvn clean && cd ..
run.sonar: 
	cd SpringMVC/ && mvn sonar:sonar && cd ..
	cd spring-rest-example/ && mvn sonar:sonar && cd ..
	cd rest-sample/ && mvn sonar:sonar && cd ..

