run.sonar:
	cd bracek-velocity-thesis/ && mvn sonar:sonar && cd ..
	cd dizetacka_veloex/ && mvn sonar:sonar && cd ..
	cd veloex/ && mvn sonar:sonar && cd ..
clean:
	cd bracek-velocity-thesis/ && mvn clean && cd ..
	cd dizetacka_veloex/ && mvn clean && cd ..
	cd veloex/ && mvn clean && cd ..
