clean.install:
	cd veloex/ && mvn clean install && cd ..
#	cd dizetacka_veloex/ && mvn clean install && cd ..
#	cd bracek-velocity-thesis/ && mvn clean install && cd ..
run.sonar:
	cd dizetacka_veloex/ && mvn sonar:sonar && cd ..
	#cd bracek-velocity-thesis/ && mvn sonar:sonar && cd ..
	cd veloex/ && mvn sonar:sonar && cd ..
clean:
	cd bracek-velocity-thesis/ && mvn clean && cd ..
	cd dizetacka_veloex/ && mvn clean && cd ..
	cd veloex/ && mvn clean && cd ..
