clean.install:
	cd ondrej/ && mvn clean install && cd ..
	cd priceIncrease/ && mvn clean install && cd ..
run.sonar:
	cd ondrej/ && mvn sonar:sonar && cd ..
clean:
	cd ondrej/ && mvn clean && cd ..
	cd priceIncrease/ && mvn clean && cd ..
